services:
  docs:
    image: portfolio_api_v1_local_docs
    container_name: portfolio_api_v1_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./portfolio_api_v1:/app/portfolio_api_v1:z
    ports:
      - '9000:9000'
    command: /start-docs
